### ISSUE TITLE
Problems occurred when I train SAC, even when I train example BC

### ISSUE THREAD

**Issue by shen-hhao** [haosulab/ManiSkill-Learn#5]
Two days ago I can train SAC and other networks properly on maniskill, but some problems suddenly occurred today
I reinstalled ManiSkill benchmark and ManiSkill-Learn but the problems are still here
Nvidia-smi works, and file /usr/share/vulkan/icd.d/nvidia_icd.json exists

Here is the problem:
When running /ManiSkill-Learn/scripts/train_rl_agent/run_SAC.sh

Traceback (most recent call last):
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/weikangwan/ManiSkill-Learn/mani_skill_learn/env/parallel_runner.py", line 43, in run
    func = self.cls(*self.args, **self.kwargs)
  File "/home/weikangwan/ManiSkill-Learn/mani_skill_learn/env/rollout.py", line 18, in __init__
    self.env = build_env(env_cfg)
  File "/home/weikangwan/ManiSkill-Learn/mani_skill_learn/env/env_utils.py", line 95, in build_env
    return build_from_cfg(cfg, ENVS, default_args)
  File "/home/weikangwan/ManiSkill-Learn/mani_skill_learn/utils/meta/registry.py", line 132, in build_from_cfg
    return obj_cls(**args)
  File "/home/weikangwan/ManiSkill-Learn/mani_skill_learn/env/env_utils.py", line 60, in make_gym_env
    env = gym.make(env_name, **tmp_kwargs)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/weikangwan/ManiSkill/mani_skill/env/open_cabinet_door_drawer.py", line 5, in <module>
    from mani_skill.env.base_env import BaseEnv
  File "/home/weikangwan/ManiSkill/mani_skill/env/base_env.py", line 59, in <module>
    _renderer = sapien.VulkanRenderer(default_mipmap_levels=1)
RuntimeError: vk::PhysicalDevice::createDeviceUnique: ErrorInitializationFailed

and when running python -m tools.run_rl configs/bc/mani_skill_point_cloud_transformer.py \
> --gpu-ids=0 --cfg-options "env_cfg.env_name=OpenCabinetDrawer_1045_link_0-v0" \
> --work-dir=./work_dirs/OpenCabinetDrawer_1045_link_0-v0 --clean-up

Traceback (most recent call last):
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/weikangwan/ManiSkill-Learn/tools/run_rl.py", line 265, in <module>
    main()
  File "/home/weikangwan/ManiSkill-Learn/tools/run_rl.py", line 254, in main
    main_mfrl_brl(cfg, args, rollout, evaluator, logger)
  File "/home/weikangwan/ManiSkill-Learn/tools/run_rl.py", line 96, in main_mfrl_brl
    agent.to('cuda')
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/torch/nn/modules/module.py", line 852, in to
    return self._apply(convert)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/weikangwan/anaconda3/envs/mani_skill/lib/python3.8/site-packages/torch/nn/modules/module.py", line 850, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

So how can I solve these problems?

**Comment by lz1oceani** [comment]
Hi shen-hhao,
From the provided error log, I guess the gpu memory may be fully occupied by other programs. To check this, you can run `nvidia-smi`. Also, you can try the maniskill environment in a python terminal before running the baselines to make sure it is possible to create a new environment object on your computer.

**Comment by shen-hhao** [comment]
I can use basic_example.py to create maniskill environment. And after using another gpu I can run bc example. But I still cannot run SAC. The problem is still there as mentioned above. And I think there is something wrong with vulkan but not with gpu memory "RuntimeError: vk::PhysicalDevice::createDeviceUnique: ErrorInitializationFailed"

**Comment by fbxiang** [comment]
1. You mentioned "another gpu". Does it mean one of the GPU is not working? If so, it will explain why vulkan and cuda both fail. `nvidia-smi` surprisingly will not tell you the GPU is broken since it is probably a driver issue, and a reboot is likely to solve it.
2. If you have a working GPU, you can set `CUDA_VISIBLE_DEVICE` to that GPU to enforce SAPIEN to use that GPU as the rendering device for vulkan. You must be on the **latest** version of SAPIEN for it to work.
3. (It probably does not matter) The existence of icd file is sometimes not enough and you need to set `VK_ICD_FILESNAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`.

**Comment by shen-hhao** [comment]
Thanks! I solved the problem by setting CUDA_VISIBLE_DEVICES to not include the not-working GPU.
